import assert from 'node:assert/strict';
import { spawnSync, execFileSync } from 'node:child_process';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const cli = path.join(root, 'src', 'cli.js');
const tmp = fs.mkdtempSync(path.join(os.tmpdir(), 'api-contract-diff-'));
const oldFile = path.join(tmp, 'old.json');
const newFile = path.join(tmp, 'new.json');
fs.writeFileSync(oldFile, JSON.stringify({ openapi: '3.0.0', paths: { '/users': { get: { responses: { 200: {} } } } }, components: { schemas: { User: { required: ['id'], properties: { id: { type: 'string' }, name: { type: 'string' } } } } } }));
fs.writeFileSync(newFile, JSON.stringify({ openapi: '3.0.0', paths: { '/users': { post: { responses: { 201: {} } } } }, components: { schemas: { User: { required: ['id', 'email'], properties: { id: { type: 'number' }, email: { type: 'string' } } } } } }));
const out = execFileSync(process.execPath, [cli, oldFile, newFile], { encoding: 'utf8' });
assert.match(out, /removed-operation/);
assert.match(out, /property-type-change/);
const failed = spawnSync(process.execPath, [cli, oldFile, newFile, '--fail-on-breaking'], { encoding: 'utf8' });
assert.equal(failed.status, 2);
console.log('api-contract-diff tests passed');
